manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  
  # ZMK modules
    - name: zmk-adaptive-key
      path: modules/zmk/adaptive-key
      
  self:
    path: config
