manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ergonautkb
      url-base: https://github.com/ergonautkb
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
<<<<<<< HEAD
    - name: ergonautkb-zmk-module
      remote: ergonautkb
      revision: main
=======
  
  # ZMK modules
    - name: zmk-helpers
      path: modules/zmk/helpers
      
>>>>>>> aa11266 (helpers)
  self:
    path: config
